language: php
php: '5.6'
install:
  - composer install --no-interaction
  - mkdir -p build/logs
script:
  - ./vendor/bin/phpunit --testsuite unit --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry php vendor/bin/coveralls -v
notifications:
  email: false
